spring:
 #  h2:
  #   console:
   #    enabled: true
  
 
  #datasource:
    #username: root
    #password: admin
    #url: jdbc:mysql://localhost/airticket

server:
  context-path: /temasek
  #port: 9090
  



  
    